### ISSUE TITLE
运行npm run serve:admin 报错

### ISSUE THREAD

**Issue by chenyanji** [huijiewei/yii2-boilerplate#19]
错误内容：

Failed to compile.

./modules/admin/main.js
Module build failed (from ../node_modules/eslint-loader/index.js):
/Users/shenying/PhpstormProjects/yii2-boilerplate/node_modules/eslint/lib/cli-engine/cli-engine.js:1015
                } catch {
                        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shenying/PhpstormProjects/yii2-boilerplate/node_modules/eslint/lib/cli-engine/index.js:3:23)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by chenyanji** [comment]
知道问题了，node要升级到12.0.0
